# Generated by Django 3.2.4 on 2021-06-07 09:48

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_main', '0003_auto_20210607_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmphurMockup',
            fields=[
            ],
            options={
                'verbose_name': 'อำเภอ',
                'verbose_name_plural': 'อำเภอ',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('service_main.amphur',),
        ),
        migrations.CreateModel(
            name='DistrictMockup',
            fields=[
            ],
            options={
                'verbose_name': 'ตำบล',
                'verbose_name_plural': 'ตำบล',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('service_main.district',),
        ),
        migrations.CreateModel(
            name='GeographyMockup',
            fields=[
            ],
            options={
                'verbose_name': 'ภูมิภาค',
                'verbose_name_plural': 'ภูมิภาค',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('service_main.geography',),
        ),
        migrations.CreateModel(
            name='ProvinceMockup',
            fields=[
            ],
            options={
                'verbose_name': 'จังหวัด',
                'verbose_name_plural': 'จังหวัด',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('service_main.province',),
        ),
    ]
