# Generated by Django 3.2.4 on 2021-06-05 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amphur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': '(ที่อยู่) อำเภอ',
                'verbose_name_plural': '(ที่อยู่) อำเภอ',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อประเภทสินค้า')),
                ('enabled', models.BooleanField(default=True, verbose_name='เปิดการใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ประเภทสินค้า',
                'verbose_name_plural': 'ประเภทสินค้า',
            },
        ),
        migrations.CreateModel(
            name='CategoryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อประเภทสินค้า')),
                ('enabled', models.BooleanField(default=True, verbose_name='เปิดการใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_main.category')),
            ],
            options={
                'verbose_name': 'ข้อมูลในประเภทสินค้า',
                'verbose_name_plural': 'ข้อมูลในประเภทสินค้า',
            },
        ),
        migrations.CreateModel(
            name='ChoiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ประเภทตัวเลือก')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ประเภทตัวเลือก',
                'verbose_name_plural': 'ประเภทตัวเลือก',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=150)),
                ('amphur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_main.amphur')),
            ],
            options={
                'verbose_name': '(ที่อยู่) ตำบล',
                'verbose_name_plural': '(ที่อยู่) ตำบล',
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='ชื่อฟาร์ม')),
                ('location', location_field.models.plain.PlainLocationField(default='19.8968 , 99.8309', max_length=63, verbose_name='แผนที่')),
                ('local', models.BooleanField(default=False, verbose_name='อาศัยอยู่ต่างประเทศ')),
                ('farm_address', models.CharField(blank=True, max_length=500, null=True, verbose_name='ที่อยู่')),
                ('zipcode', models.CharField(blank=True, max_length=500, null=True, verbose_name='รหัสไปรษณีย์')),
                ('farm_image', models.ImageField(blank=True, null=True, upload_to='Farm_image/', verbose_name='ภาพถ่ายฟาร์ม')),
                ('email', models.CharField(blank=True, max_length=500, null=True, verbose_name='อีเมล์ร้าน')),
                ('facebook', models.CharField(blank=True, max_length=500, null=True)),
                ('line', models.CharField(blank=True, max_length=500, null=True, verbose_name='ไลน์')),
                ('tel', models.CharField(blank=True, max_length=500, null=True, verbose_name='เบอร์โทรฟาร์ม')),
                ('other', models.CharField(blank=True, max_length=500, null=True, verbose_name='การติดต่ออื่นๆ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amphur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_main.amphur', verbose_name='อำเภอ')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_main.district', verbose_name='ตำบล')),
            ],
            options={
                'verbose_name': 'ข้อมูลฟาร์ม',
                'verbose_name_plural': 'ข้อมูลฟาร์ม',
            },
        ),
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '(ที่อยู่) ภูมิภาค',
                'verbose_name_plural': '(ที่อยู่) ภูมิภาค',
            },
        ),
        migrations.CreateModel(
            name='GroupsFarmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='ชื่อกลุ่ม')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'กลุ่มเกษตรกร',
                'verbose_name_plural': 'กลุ่มเกษตรกร',
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อสถานที่สำคัญ')),
                ('address', models.TextField(blank=True, null=True, verbose_name='ที่อยู่')),
                ('location', location_field.models.plain.PlainLocationField(default='19.8968 , 99.8309', max_length=63, verbose_name='แผนที่')),
                ('other', models.TextField(blank=True, null=True, verbose_name='อื่นๆ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'สถานที่สำคัญ',
                'verbose_name_plural': 'สถานที่สำคัญ',
            },
        ),
        migrations.CreateModel(
            name='ProductStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.IntegerField(blank=True, choices=[(0, 'ขาย'), (1, 'ซื้อ')], null=True)),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อสถานะสินค้า')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'สถานะสินค้า',
                'verbose_name_plural': 'สถานะสินค้า',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=150)),
                ('geo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_main.geography')),
            ],
            options={
                'verbose_name': '(ที่อยู่) จังหวัด',
                'verbose_name_plural': '(ที่อยู่) จังหวัด',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(blank=True, choices=[('นาย', 'นาย'), ('นาง', 'นาง'), ('นางสาว', 'นางสาว')], max_length=255, null=True, verbose_name='คำนำหน้า')),
                ('gender', models.CharField(blank=True, choices=[('ชาย', 'ชาย'), ('หญิง', 'หญิง')], max_length=255, null=True, verbose_name='เพศ')),
                ('personal_id', models.CharField(blank=True, max_length=255, verbose_name='เลขบัตรประจำตัวประชาชน')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='Profile_image/', verbose_name='รูปโปรไฟล์')),
                ('presonal_image', models.ImageField(blank=True, null=True, upload_to='Personal_image/', verbose_name='สำเนาบัตรประจำตัวประชาชน')),
                ('local', models.BooleanField(default=False, verbose_name='อาศัยอยู่ต่างประเทศ')),
                ('zipcode', models.CharField(blank=True, max_length=500, verbose_name='รหัสไปรษณีย์')),
                ('birthday', models.DateField(verbose_name='วันเกิด')),
                ('age', models.FloatField(verbose_name='อายุ')),
                ('status', models.BooleanField(default=True, verbose_name='สถานะการใช้งาน')),
                ('email', models.CharField(blank=True, max_length=500, null=True, verbose_name='อีเมล์อื่นๆ')),
                ('facebook', models.CharField(blank=True, max_length=500, null=True)),
                ('line', models.CharField(blank=True, max_length=500, null=True)),
                ('tel', models.CharField(blank=True, max_length=500, null=True, verbose_name='เบอร์โทร')),
                ('other', models.CharField(blank=True, max_length=500, null=True, verbose_name='การติดต่ออื่นๆ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amphur', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='province', chained_model_field='province', on_delete=django.db.models.deletion.CASCADE, to='service_main.amphur', verbose_name='อำเภอ')),
                ('district', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='amphur', chained_model_field='amphur', on_delete=django.db.models.deletion.CASCADE, to='service_main.district', verbose_name='ตำบล')),
                ('geo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_main.geography', verbose_name='ภูมิภาค')),
                ('province', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='geo', chained_model_field='geo', on_delete=django.db.models.deletion.CASCADE, to='service_main.province', verbose_name='จังหวัด')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้')),
            ],
            options={
                'verbose_name': 'ข้อมูลผู้ใช้งานทั่วไป',
                'verbose_name_plural': 'ข้อมูลผู้ใช้งานทั่วไป',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อสินค้า')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='รายระเอียดสินค้า')),
                ('product_type', models.IntegerField(blank=True, choices=[(0, 'ขาย'), (1, 'ซื้อ')], default=0, null=True, verbose_name='ประเภทสินค้า ซื้อ/ขาย')),
                ('price_type', models.BooleanField(choices=[(True, 'ราคาเต็ม'), (False, 'ช่วงราคา')], default=True, verbose_name='ประเภทราคา')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='ราคาสินค้า (ราคาเต็ม)')),
                ('price_start', models.FloatField(blank=True, null=True, verbose_name='ช่วงราคาต่ำสุด (ช่วงราคา)')),
                ('price_end', models.FloatField(blank=True, null=True, verbose_name='ช่วงราคาสูงสุด (ช่วงราคา)')),
                ('file1', models.FileField(blank=True, null=True, upload_to='product/', verbose_name='รูปสินค้า หรือวีดีโอ')),
                ('file2', models.FileField(blank=True, null=True, upload_to='product/', verbose_name='รูปสินค้า หรือวีดีโอ')),
                ('file3', models.FileField(blank=True, null=True, upload_to='product/', verbose_name='รูปสินค้า หรือวีดีโอ')),
                ('file4', models.FileField(blank=True, null=True, upload_to='product/', verbose_name='รูปสินค้า หรือวีดีโอ')),
                ('file5', models.FileField(blank=True, null=True, upload_to='product/', verbose_name='รูปสินค้า หรือวีดีโอ')),
                ('sell_type', models.IntegerField(blank=True, choices=[(0, 'ชั่วคราว'), (1, 'ถาวร')], null=True, verbose_name='ประเภทการขาย *ประกาศขาย')),
                ('buy_date', models.DateField(blank=True, null=True, verbose_name='วันที่ปิดการขาย *ประกาศซื้อ')),
                ('status', models.IntegerField(blank=True, choices=[(5, 'มีสินค้า'), (4, 'สินค้าหมด'), (3, 'ขายแล้ว'), (1, 'รับซื้อ'), (2, 'ได้รับสินค้าแล้ว'), (0, 'ยกเลิก')], null=True, verbose_name='สถานะสินค้า')),
                ('enabled', models.BooleanField(default=True, verbose_name='เปิดการใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(to='service_main.CategoryDetail', verbose_name='ประเภทสินค้า')),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_main.farm', verbose_name='ร้านค้า')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='เจ้าของ')),
            ],
            options={
                'verbose_name': 'ประกาศ ซื้อ/ขาย',
                'verbose_name_plural': 'ประกาศ ซื้อ/ขาย',
            },
        ),
        migrations.AddField(
            model_name='farm',
            name='geo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_main.geography', verbose_name='ภูมิภาค'),
        ),
        migrations.AddField(
            model_name='farm',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='service_main.groupsfarmer', verbose_name='กลุ่มเกษตรกร'),
        ),
        migrations.AddField(
            model_name='farm',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_main.province', verbose_name='จังหวัด'),
        ),
        migrations.AddField(
            model_name='farm',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='เจ้าของฟาร์ม'),
        ),
        migrations.AddField(
            model_name='district',
            name='geo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_main.geography'),
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_main.province'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='ชื่อตัวเลือก')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_main.choicetype')),
            ],
            options={
                'verbose_name': 'ตัวเลือก',
                'verbose_name_plural': 'ตัวเลือก',
            },
        ),
        migrations.AddField(
            model_name='amphur',
            name='geo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_main.geography'),
        ),
        migrations.AddField(
            model_name='amphur',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_main.province'),
        ),
    ]
