# Generated by Django 3.2.4 on 2021-06-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='value_ch',
            field=models.CharField(max_length=255, null=True, verbose_name='ชื่อตัวเลือก'),
        ),
        migrations.AddField(
            model_name='choice',
            name='value_en',
            field=models.CharField(max_length=255, null=True, verbose_name='ชื่อตัวเลือก'),
        ),
        migrations.AddField(
            model_name='choice',
            name='value_th',
            field=models.CharField(max_length=255, null=True, verbose_name='ชื่อตัวเลือก'),
        ),
        migrations.AddField(
            model_name='choicetype',
            name='name_ch',
            field=models.CharField(max_length=255, null=True, verbose_name='ประเภทตัวเลือก'),
        ),
        migrations.AddField(
            model_name='choicetype',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='ประเภทตัวเลือก'),
        ),
        migrations.AddField(
            model_name='choicetype',
            name='name_th',
            field=models.CharField(max_length=255, null=True, verbose_name='ประเภทตัวเลือก'),
        ),
    ]
