# Generated by Django 3.2.4 on 2021-06-07 12:12

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('service_main', '0003_auto_20210607_0948'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductStatus',
        ),
        migrations.AlterField(
            model_name='profile',
            name='amphur',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='province', chained_model_field='province', null=True, on_delete=django.db.models.deletion.CASCADE, to='service_main.amphur', verbose_name='อำเภอ'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='district',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='amphur', chained_model_field='amphur', null=True, on_delete=django.db.models.deletion.CASCADE, to='service_main.district', verbose_name='ตำบล'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='geo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_main.geography', verbose_name='ภูมิภาค'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='province',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='geo', chained_model_field='geo', null=True, on_delete=django.db.models.deletion.CASCADE, to='service_main.province', verbose_name='จังหวัด'),
        ),
    ]
