# Generated by Django 3.2.4 on 2021-06-07 09:48

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_main', '0003_auto_20210607_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMockup',
            fields=[
            ],
            options={
                'verbose_name': 'ประกาศ ซื้อ/ขาย',
                'verbose_name_plural': 'ประกาศ ซื้อ/ขาย',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('service_main.product',),
        ),
    ]
