# Generated by Django 3.2.4 on 2021-06-07 09:48

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_main', '0003_auto_20210607_0948'),
        ('drf_api_logger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogerReport',
            fields=[
            ],
            options={
                'verbose_name': 'รายงานความเคลื่อนไหว',
                'verbose_name_plural': 'รายงานความเคลื่อนไหว',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('drf_api_logger.apilogsmodel',),
        ),
        migrations.CreateModel(
            name='Products_Report',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('service_main.product',),
        ),
    ]
