# Generated by Django 3.2.4 on 2021-06-07 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_main', '0004_auto_20210607_1212'),
        ('app_report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_Report',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('service_main.profile',),
        ),
    ]
