# Generated by Django 3.2.4 on 2021-06-07 09:48

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_main', '0003_auto_20210607_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMockup',
            fields=[
            ],
            options={
                'verbose_name': 'สินค้า (ประเภท)',
                'verbose_name_plural': 'สินค้า (ประเภท)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('service_main.category',),
        ),
        migrations.CreateModel(
            name='ChoiceMockup',
            fields=[
            ],
            options={
                'verbose_name': 'ตัวเลือก',
                'verbose_name_plural': 'ตัวเลือก',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('service_main.choicetype',),
        ),
        migrations.CreateModel(
            name='GroupFarmerMockup',
            fields=[
            ],
            options={
                'verbose_name': 'กลุ่มเกษตรกร',
                'verbose_name_plural': 'กลุ่มเกษตรกร',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('service_main.groupsfarmer',),
        ),
        migrations.CreateModel(
            name='ProductStatusMockup',
            fields=[
            ],
            options={
                'verbose_name': 'สินค้า (สถานะ)',
                'verbose_name_plural': 'สินค้า (สถานะ)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('service_main.productstatus',),
        ),
    ]
