# Generated by Django 3.2.4 on 2021-06-07 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_webconfig', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductStatusMockup',
        ),
    ]
